set dotenv-load

deploy_host := "$HOST"

unbound-log:
  docker context use dns1
  docker exec -it unbound tail -f /opt/unbound/etc/unbound/unbound.log

deploy:
  docker context create dns1 --docker "host=ssh://{{deploy_host}}" || true
  docker context use dns1
  scp -r bind9 {{deploy_host}}:$BASE_DIR
  scp -r unbound {{deploy_host}}:$BASE_DIR
  BASE_DIR=$BASE_DIR docker compose up -d --force-recreate
