---
networks:
  mempool:
    ipam:
      driver: default
      config:
        - subnet: "172.23.0.0/24"
services:
  web:
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
    environment:
      FRONTEND_HTTP_PORT: "8050"
      BACKEND_MAINNET_HTTP_HOST: "api"
    image: mempool/frontend:latest
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for db:3306 --timeout=720 -- nginx -g 'daemon off;'"
    ports:
      - 8050:8050
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - mempool
  api:
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
    environment:
      MEMPOOL_BACKEND: "none"
      ELECTRUM_HOST: "${ELECTRUM_HOST}"
      ELECTRUM_PORT: "50002"
      ELECTRUM_TLS_ENABLED: "true"
      CORE_RPC_HOST: "${CORE_RPC_HOST}"
      CORE_RPC_PORT: "${CORE_RPC_PORT}"
      CORE_RPC_USERNAME: "${CORE_RPC_USERNAME}"
      CORE_RPC_PASSWORD: "${CORE_RPC_PASSWORD}"
      DATABASE_ENABLED: "true"
      DATABASE_HOST: "db"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "${DATABASE_USERNAME}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      STATISTICS_ENABLED: "true"
    image: mempool/backend:latest
    # user: "1002:${GID}"
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for-it.sh db:3306 --timeout=720 --strict -- ./start.sh"
    volumes:
      - ${BASE_DIR:-.}/data:/backend/cache
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - mempool
  db:
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "${DATABASE_USERNAME}"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    image: mariadb:10.5.21
    user: "1002:${GID}"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${BASE_DIR:-.}/mysql/data:/var/lib/mysql
    networks:
      - mempool
