set dotenv-load

deploy_host := "$HOST-docker"

set-context:
  @echo "(+) Setting Docker context..."
  @docker context create {{deploy_host}} --docker "host=ssh://{{deploy_host}}" || true
  @docker context use {{deploy_host}}

deploy: set-context
  BASE_DIR=$BASE_DIR docker compose up -d --force-recreate

tunnel:
  @echo "opening SSH tunnel..."
  @echo "Visit http://localhost:8050"
  ssh -N -L 127.0.0.1:8050:127.0.0.1:8050 {{deploy_host}}

logs:
  docker compose logs -f
