# Ref: https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/
[server]
# The public facing domain name used to access grafana from a browser
; domain = grafana.local.${DOMAIN}

# The full public facing url you use in browser, used for redirects and emails
# If you use reverse proxy and sub path specify full url (with sub path)
root_url = https://%(domain)s/

[smtp]
enabled = true
host = postfix:25
skip_verify = true
