---
version: '3'
networks:
  synapse:
services:
  matrix-nginx:
    image: nginx@sha256:270bea203d2fc3743fb9ce0193325e188b7e6233043487e3d3cf117ea4d3f337
    container_name: matrix-nginx
    restart: unless-stopped
    ports:
     - 8008:80/tcp
    networks:
       synapse:
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://localhost || exit 1"]
      timeout: 10s
    entrypoint:
      - sh
      - -euc
      - |
        cat <<EOF > /etc/nginx/conf.d/default.conf
        server {
          listen 80;
          access_log /dev/stdout;
          error_log /dev/stdout;

          location / {
            proxy_pass http://matrix-synapse:8008;
          }

          location /_synapse/admin {
            return 403 'Not available';
          }

          error_page 500 502 503 504 /50x.html;
          location = /50x.html {
            root /usr/share/nginx/html;
          }
        }
        EOF
        nginx -g "daemon off;"
    depends_on:
      - matrix-synapse

  matrix-synapse:
    image: matrixdotorg/synapse@sha256:dce2c712f36c9f714ad2895c0773286620d96374d8143a52f148271e07eb9509
    container_name: matrix-synapse
    restart: unless-stopped
    environment:
      # https://github.com/matrix-org/synapse/tree/develop/docker#generating-a-configuration-file
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - UID=1000
      - GID=1000
    # ports:
     # - 8448:8448/tcp
     # - 8008:8008/tcp
    volumes:
      - ${BASE_DIR:-.}/synapse/data:/data
    networks:
       synapse:
    healthcheck:
      test: ["CMD", "curl", "-fSs", "http://localhost:8008/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s
    depends_on:
      - matrix-synapse-db

  matrix-synapse-db:
    image: docker.io/postgres@sha256:96c1413ba7871a0f3480034a41aca641f0ad1f724eb50f5d8ed668a51b9b22ad
    container_name: matrix-synapse-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-matrixisawesome}"
      - POSTGRES_DB=synapse
      # https://github.com/matrix-org/synapse/blob/master/docs/postgres.md#set-up-database
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ${BASE_DIR:-.}/synapse/db:/var/lib/postgresql/data
    # ports:
    #   - 5432:5432
    networks:
       synapse:

  matrix-postfix:
    image: boky/postfix@sha256:4b7e77349a09779b7fea281db2f113e66da69cdc362fbfb55fbc8c5716952d16
    container_name: matrix-postfix
    restart: unless-stopped
    environment:
      - "ALLOWED_SENDER_DOMAINS=${MATRIX_DOMAIN:-matrix.org}"
    # ports:
    #   - 1587:587
    networks:
       synapse:
