---
- name: reload systemd
  command: systemctl daemon-reload

- name: restart fulcrum
  systemd:
    name: fulcrum
    state: restarted

- name: restart tor
  systemd:
    name: tor
    state: restarted

- name: cleanup fulcrum files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/fulcrum
