--- 
services:
  caddy:
    container_name: caddy
    build:
      context: .
      dockerfile: caddy.dockerfile
      args:
        - CADDY_VERSION=${CADDY_VERSION:-2.10.0}
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    environment:
      CF_API_EMAIL: "${CF_API_EMAIL}"
      CF_API_KEY: "${CF_API_KEY}"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    entrypoint:
      - sh
      - -euc
      - |
        cat <<EOF > /etc/caddy/Caddyfile
        {
          email "${CF_API_EMAIL}"
          cache
          log {
            level debug
          }
        }
        *.local.${DOMAIN} {
          tls {
              issuer acme {
                  dns cloudflare ${CF_API_KEY}
                  resolvers 1.1.1.1 1.0.0.1
              }
          }

          @audiobookshelf host audiobookshelf.local.${DOMAIN}
          handle @audiobookshelf {
            cache
            reverse_proxy ${SERVER}:2008
          }

          @authentik host authentik.local.${DOMAIN}
          handle @authentik {
            cache
            reverse_proxy ${SERVER3}:9000 {
              header_up Host {http.reverse_proxy.upstream.hostport}
            }
          }

          @btcexplorer host btcexplorer.local.${DOMAIN}
          handle @btcexplorer {
            cache
            reverse_proxy ${SERVER3}:3002
          }

          @cryptpad host cryptpad.local.${DOMAIN}
          handle @cryptpad {
            cache
            reverse_proxy ${SERVER3}:3128
          }

          @gatus host gatus.local.${DOMAIN}
          handle @gatus {
            cache
            reverse_proxy ${SERVER}:8076
          }

          @fulcrum host fulcrum.local.${DOMAIN}
          handle @fulcrum {
            reverse_proxy ${SERVER}:50002
          }

          @grafana host grafana.local.${DOMAIN}
          handle @grafana {
            cache
            reverse_proxy ${SERVER5}:3000
          }

          @influxdb host influxdb.local.${DOMAIN}
          handle @influxdb {
            cache
            reverse_proxy ${SERVER5}:8086
          }

          @otel host otel.local.${DOMAIN}
          handle @otel {
            cache
            reverse_proxy ${SERVER5}:4318
          }

          @jellyfin host jellyfin.local.${DOMAIN}
          handle @jellyfin {
            cache
            reverse_proxy ${NAS}:8096
          }

          @navidrome host navidrome.local.${DOMAIN}
          handle @navidrome {
            reverse_proxy ${SERVER3}:4553
          }

          @nas host nas.local.${DOMAIN}
          handle @nas {
            cache
            reverse_proxy ${NAS}:8080
          }

          @portainer-nas host portainer-nas.local.${DOMAIN}
          handle @portainer-nas {
            cache
            reverse_proxy https://${NAS}:19943 {
              transport http {
                tls
                tls_insecure_skip_verify
              }
            }
          }

          @pve1 host pve1.local.${DOMAIN}
          handle @pve1 {
            cache
            reverse_proxy https://${PSERVER}:8006 {
              transport http {
                tls
                tls_insecure_skip_verify
              }
            }
          }

          @search host search.local.${DOMAIN}
          handle @search {
            cache
            reverse_proxy ${SERVER}:6080
          }

          @uptime-kuma host uptime-kuma.local.${DOMAIN}
          handle @uptime-kuma {
            cache
            reverse_proxy http://uptime-kuma.homelab.local.${DOMAIN}
          }

          @cp host cp.local.${DOMAIN}
          handle @cp {
            cache
            reverse_proxy ${NAS}:3923
          }

          @music host music.local.${DOMAIN}
          handle @music {
            cache
            reverse_proxy ${SERVER}:4553
          }

          @mempool host mempool.local.${DOMAIN}
          handle @mempool {
            cache
            reverse_proxy ${SERVER}:8050
          }

          @test host test.local.${DOMAIN}
          handle @test {
            respond "hello world"
          }

          @joplin host joplin.local.${DOMAIN}
          handle @joplin {
            reverse_proxy ${SERVER4}:22300
          }

          @ollama host ollama.local.${DOMAIN}
          handle @ollama {
            handle @token {
              reverse_proxy ${SERVER}:11434
            }
            respond "Unauthorized" 401
          }

          @token {
            header Authorization "Bearer ${TOKEN}"
          }

          @cachenixos host cachenixos.local.${DOMAIN}
          handle @cachenixos {
            cache {
                ttl 90d
            }
            reverse_proxy https://cache.nixos.org {
              header_up Host {upstream_hostport}
              header_up X-Forwarded-Host {upstream_hostport}
            }
          }

          # default
          respond "No page found" 404
        }
        EOF
        caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
 
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "8080:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "4443:443/tcp"
    environment:
      # Set the appropriate timezone for your location from
      # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones, e.g:
      TZ: '${TZ}'
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      FTLCONF_webserver_api_password: '${PIHOLE_PASSWORD}'
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'ALL'
      FTLCONF_dns_listeningMode: 'ALL'
    # Volumes store your data between container upgrades
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - 'pihole_config:/etc/pihole'
    restart: unless-stopped
volumes:
  caddy_data:
  caddy_config:
  pihole_config:
