--- 
services:
  caddy:
    container_name: caddy
    build:
      context: .
      dockerfile: caddy.dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    environment:
      CF_API_EMAIL: "${CF_API_EMAIL}"
      CF_API_KEY: "${CF_API_KEY}"
    entrypoint:
      - sh
      - -euc
      - |
        cat <<EOF > /etc/caddy/Caddyfile
        {
          email "${CF_API_EMAIL}"
          cache
        }
        *.local.${DOMAIN} {
          tls {
              issuer acme {
                  dns cloudflare ${CF_API_KEY}
                  resolvers 1.1.1.1 1.0.0.1
              }
          }

          @audiobookshelf host audiobookshelf.local.${DOMAIN}
          handle @audiobookshelf {
            cache
            reverse_proxy ${SERVER}:2008
          }

          @authentik host authentik.local.${DOMAIN}
          handle @authentik {
            cache
            reverse_proxy ${SERVER3}:9000 {
              header_up Host {http.reverse_proxy.upstream.hostport}
            }
          }

          @btcexplorer host btcexplorer.local.${DOMAIN}
          handle @btcexplorer {
            cache
            reverse_proxy ${SERVER3}:3002
          }

          @cryptpad host cryptpad.local.${DOMAIN}
          handle @cryptpad {
            cache
            reverse_proxy ${SERVER3}:3128
          }

          @gatus host gatus.local.${DOMAIN}
          handle @gatus {
            cache
            reverse_proxy ${SERVER}:8076
          }

          @grafana host grafana.local.${DOMAIN}
          handle @grafana {
            cache
            reverse_proxy ${SERVER3}:3000
          }

          @influxdb host influxdb.local.${DOMAIN}
          handle @influxdb {
            cache
            reverse_proxy ${SERVER3}:8086
          }

          @jellyfin host jellyfin.local.${DOMAIN}
          handle @jellyfin {
            cache
            reverse_proxy ${NAS}:8096
          }

          @navidrome host navidrome.local.${DOMAIN}
          handle @navidrome {
            reverse_proxy ${SERVER3}:4553
          }

          @nas host nas.local.${DOMAIN}
          handle @nas {
            cache
            reverse_proxy ${NAS}:8080
          }

          @portainer-nas host portainer-nas.local.${DOMAIN}
          handle @portainer-nas {
            cache
            reverse_proxy https://${NAS}:19943 {
              transport http {
                tls
                tls_insecure_skip_verify
              }
            }
          }

          @proxmox host proxmox.local.${DOMAIN}
          handle @proxmox {
            cache
            reverse_proxy ${PSERVER}:8006
          }

          @uptime-kuma host uptime-kuma.local.${DOMAIN}
          handle @uptime-kuma {
            cache
            reverse_proxy http://uptime-kuma.homelab.local.${DOMAIN}
          }

          @test host test.local.${DOMAIN}
          handle @test {
            respond "hello world"
          }
        }
        EOF
        caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
 
volumes:
  caddy_data:
  caddy_config:
