set dotenv-load

deploy_host := "$HOST"

yeet-files:
  @find . -maxdepth 1 -type d -not -name . | while read dir; do scp -r "$dir" {{deploy_host}}:$BASE_DIR; done

set-context:
  @echo "(+) Setting Docker context..."
  @docker context create {{deploy_host}} --docker "host=ssh://{{deploy_host}}" || true
  @docker context use {{deploy_host}}

deploy: set-context yeet-files
  docker compose up -d --force-recreate
  docker compose ps

connect:
  @echo "Establishing SSH tunnel..."
  ssh -fNL 443:localhost:443 $HOST
  xdg-open https://localhost

save-secrets:
  sops -e .env > .env.enc

test:
  bats test
