---
services:
  multi-scrobbler:
    image: foxxmd/multi-scrobbler
    container_name: multi-scrobbler
    environment:
      - TZ=${TZ} # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - LASTFM_API_KEY=${LASTFM_API_KEY}
      - LASTFM_SECRET=${LASTFM_SECRET}
      - LZ_TOKEN=${LZ_TOKEN}
      - LZ_USER=${LZ_USER}
      - PUID=${UID}
      - PGID=${GID}
      - BASE_URL=${BASE_URL}
    volumes:
      - "${BASE_DIR:-.}/multi-scrobbler/config:/config"
    ports:
      - 9078:9078 
    restart: unless-stopped
