- name: reload systemd
  command: systemctl daemon-reload

- name: start albyhub
  systemd:
    name: albyhub
    state: started

# - name: cleanup albyhub
#   file:
#     path: "{{ item }}"
#     state: absent
#   with_items:
#     - "{{ albyhub_dl_dir }}"
