---
- hosts: all
  become: true
  pre_tasks:
    - name: update repository index (ubuntu)
      tags: always
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"

- hosts: all
  vars_files:
    - "./vars/vault.yml"
  become: true
  roles:
    - base

- hosts: all
  vars_files:
    - "./vars/vault.yml"
  become: true
  roles:
    - docker_hosts
  tags:
    - docker

- hosts: all
  vars_files:
    - "./vars/vault.yml"
  become: true
  roles:
    - tailscale
  tags:
    - tailscale

- name: Install bitcoin-core
  become: true
  hosts: all
  vars:
    version: "27.0" # https://bitcoin.org/en/download
    fulcrum_version: "1.11.1"
  vars_files:
    - "./vars/vault.yml"
  roles:
    - bitcoin-core
  tags:
    - bitcoin-core
    - fulcrum
