---
- hosts: all
  become: true
  pre_tasks:
    - name: update repository index (ubuntu)
      tags: always
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"

- hosts: all
  vars_files:
    - "./vars/vault.yml"
  become: true
  roles:
    - base

- hosts: docker_hosts
  vars_files:
    - "./vars/vault.yml"
  become: true
  roles:
    - docker_hosts
  tags:
    - docker

- hosts: tailscale
  vars_files:
    - "./vars/vault.yml"
  become: true
  roles:
    - tailscale
  tags:
    - tailscale

- name: Install Caddy
  hosts: caddy
  vars:
    caddy_deb_url: "https://github.com/caddyserver/caddy/releases/download/v2.8.4/caddy_2.8.4_linux_amd64.deb" # https://github.com/caddyserver/caddy/releases
  vars_files:
    - "./vars/vault.yml"
  roles:
    - caddy
  tags:
    - caddy
