---
- hosts: all
  become: true
  pre_tasks:
    - name: update repository index (ubuntu)
      tags: always
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"

- hosts: all
  vars_files:
    - "./vars/vault.yml"
  become: true
  roles:
    - base

- hosts: docker_hosts
  vars_files:
    - "./vars/vault.yml"
  become: true
  roles:
    - docker_hosts
  tags:
    - docker

- hosts: tailscale
  vars_files:
    - "./vars/vault.yml"
  become: true
  roles:
    - tailscale
  tags:
    - tailscale

- name: Install bitcoin-core
  hosts: bitcoin-core
  vars:
    version: "27.0" # https://bitcoin.org/en/download
  vars_files:
    - "./vars/vault.yml"
  roles:
    - bitcoin-core
  tags:
    - bitcoin-core

- name: Install dojo
  hosts: dojo
  vars_files:
    - "./vars/vault.yml"
  roles:
    - dojo
  tags:
    - dojo
