---
- hosts: all
  become: true
  pre_tasks:
    - name: update repository index (ubuntu)
      tags: always
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"

- hosts: all
  vars_files:
    - "./vars/vault.yml"
  become: true
  roles:
    - base

- hosts: docker_hosts
  vars_files:
    - "./vars/vault.yml"
  become: true
  roles:
    - docker_hosts
  tags:
    - docker
