version: "3"
networks:
  matrix_synapse:
    external: true
services:
  mautrix-signal:
    container_name: mautrix-signal
    image: dock.mau.dev/mautrix/signal@sha256:f8f64e47340162040f1482e699766a6b6067fe15d42f5788a6478ae6e50d7724
    restart: unless-stopped
    networks:
      matrix_synapse:
    volumes:
      - ${BASE_DIR:-.}/mautrix-signal/data:/data
    environment:
      - UID=1000
      - GID=1000
    depends_on:
      - mautrix-signal-db

  mautrix-signal-db:
    image: docker.io/postgres@sha256:96c1413ba7871a0f3480034a41aca641f0ad1f724eb50f5d8ed668a51b9b22ad
    container_name: mautrix-signal-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mautrix-signal
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ${BASE_DIR:-.}/mautrix-signal/db:/var/lib/postgresql/data
    # ports:
    #   - 5432:5432
    networks:
      matrix_synapse:
