---
alerting:
  ntfy:
    url: "${NTFY_URL}"
    topic: "${NTFY_TOPIC}"
    priority: 1
    default-alert:
      failure-threshold: 3
      send-on-resolved: true

connectivity:
  checker:
    target: 9.9.9.9:53
    interval: 60s
