set dotenv-load

deploy_host := "$HOST-docker"

set-context:
  @echo "(+) Setting Docker context..."
  @docker context create {{deploy_host}} --docker "host=ssh://{{deploy_host}}" || true
  @docker context use {{deploy_host}}

deploy: set-context
  BASE_DIR=$BASE_DIR docker compose up -d --force-recreate
