- name: Download Caddy deb file
  get_url:
    url: "https://github.com/caddyserver/caddy/releases/download/v{{ caddy_version }}/caddy_{{ caddy_version }}_linux_amd64.deb"
    dest: /tmp/caddy_{{ caddy_version }}_linux_amd64.deb
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: Install Caddy deb file
  apt:
    deb: /tmp/caddy_{{ caddy_version }}_linux_amd64.deb
    state: present
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: Change ownership of /etc/caddy to caddy:caddy
  file:
    path: /etc/caddy
    owner: caddy
    group: caddy
    mode: 0755

- name: Download Caddy server binary with cloudflare module
  get_url:
    url: "https://caddyserver.com/api/download?os=linux&arch=amd64&p=github.com%2Fcaddy-dns%2Fcloudflare"
    dest: /usr/bin/caddy
    mode: '0755'
  become: yes

- name: Create Caddyfile
  template:
    src: templates/Caddyfile.j2
    dest: /etc/caddy/Caddyfile
  become: yes
  become_user: caddy
  notify:
    - Restart caddy
    - Validate caddy
