- name: Download Caddy deb file
  get_url:
    url: "{{ caddy_deb_url }}"
    dest: /tmp/caddy_2.8.4_linux_amd64.deb
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: Install Caddy deb file
  apt:
    deb: /tmp/caddy_2.8.4_linux_amd64.deb
    state: present
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: Change ownership of /etc/caddy to caddy:caddy
  file:
    path: /etc/caddy
    owner: caddy
    group: caddy
    mode: 0755

- name: Create Caddyfile
  template:
    src: templates/Caddyfile.j2
    dest: /etc/caddy/Caddyfile
  become: yes
  become_user: caddy
  notify:
    - Restart caddy
    - Validate caddy
