---
networks:
  forgejo:
    external: false

services:
  server:
    image: codeberg.org/forgejo/forgejo:13
    container_name: forgejo
    environment:
      - USER_UID=${UID}
      - USER_GID=${GID}
      - TZ=${TZ} # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    restart: always
    networks:
      - forgejo
    volumes:
      - "${BASE_DIR:-.}/forgejo:/data"
    ports:
      - '2000:3000'
      - '22:22'
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
