---
networks:
  navidrome:
services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: ${UID}:${GID} # should be owner of volumes
    ports:
      - "4553:80"
    restart: unless-stopped
    environment:
      ND_SCANNER_ENABLED: true
      ND_SCANSCHEDULE: "0 */2 * * *"
      ND_SCANNER_PURGEMISSING: "always"
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
      ND_PORT: 80
    volumes:
      - type: bind
        source: ${BASE_DIR:-.}/navidrome/data
        target: /data
        bind:
          create_host_path: true
      - type: bind
        source: ${MUSIC_SHARE_DIR}
        target: /music
        read_only: true
        bind:
          create_host_path: true
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    networks:
      - navidrome
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
