networks:
  navidrome:
services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: ${UID}:${GID} # should be owner of volumes
    # ports:
    #   - "4553:80"
    restart: unless-stopped
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
      ND_PORT: 80
    volumes:
      - "${BASE_DIR:-.}/navidrome/data:/data"
      - "${MUSIC_SHARE_DIR}:/music:ro"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    network_mode: service:ts-navidrome
    depends_on:
      - ts-navidrome

  ts-navidrome:
    container_name: ts-navidrome
    image: tailscale/tailscale:stable
    hostname: navidrome
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_EXTRA_ARGS=--login-server=https://${TS_DOMAIN}
      - TS_NO_LOGS_NO_SUPPORT=true
      # - TS_AUTHKEY=${TS_AUTHKEY} 
    volumes:
      - ts-navidrome-vol:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    networks:
      - navidrome
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "4553:80"

volumes:
  ts-navidrome-vol: {}
