extensions:
  health_check: {}
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  httpcheck:
    targets:
      - endpoint: http://grafana:3000/healthz
        method: GET
    collection_interval: 10s
processors:
  batch:
exporters:
  otlp:
    endpoint: telegraf:4317
    tls:
      insecure: true
  debug:
    verbosity: detailed
service:
  pipelines:
    metrics:
      receivers: [otlp, httpcheck]
      processors: [batch]
      exporters: [debug, otlp]
