set dotenv-load

deploy_host := "$HOST-docker"

set-context:
  @echo "(+) Setting Docker context..."
  @docker context create {{deploy_host}} --docker "host=ssh://{{deploy_host}}" || true
  @docker context use {{deploy_host}}

build: set-context
  @echo "(+) Building Docker image..."
  @git clone --quiet --depth 1 https://github.com/janoside/btc-rpc-explorer.git
  @cd btc-rpc-explorer && docker build -t btc-rpc-explorer .
  @rm -rf btc-rpc-explorer
  @docker images | grep btc-rpc-explorer

deploy: set-context
  @echo "(+) Deploying..."
  BASE_DIR=$BASE_DIR docker compose up -d --force-recreate
  docker compose ps

get-hostname:
  @docker exec -it btc-rpc-tor cat /home/tor/.tor/btc-rpc-explorer/hostname
