---
- name: install sudo
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
  with_items:
    - sudo
  when: ansible_distribution == "Debian"

- name: add group
  ansible.builtin.group:
    name: "{{ admin_group }}"
    state: present

- name: Add local user
  user:
    name: "{{ admin_user }}"
    group: "{{ admin_group }}"
    password: "{{ admin_password_hashed }}"
    shell: /bin/bash
    home: "/home/{{ admin_user }}"
    create_home: yes
    state: present

- name: sudo without password for admin group
  copy:
    content: "%{{ admin_group }} ALL=(ALL:ALL) NOPASSWD:ALL"
    dest: /etc/sudoers.d/admin_nopasswd
    mode: 0440

- name: Add SSH public key for user
  authorized_key:
    user: "{{ admin_user }}"
    key: "{{ admin_ssh_public_key }}"
    state: present

- name: install "rsyslog" package
  become: true
  ansible.builtin.apt:
    name: rsyslog
  when: ansible_distribution == "Debian"

- name: install "ufw" package
  become: true
  ansible.builtin.apt:
    name: ufw
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- ufw:
    rule: allow
    name: OpenSSH

# ufw supports connection rate limiting, which is useful for protecting
# against brute-force login attacks. ufw will deny connections if an IP
# address has attempted to initiate 6 or more connections in the last
# 30 seconds. See  http://www.debian-administration.org/articles/187
# for details. Typical usage is:
- ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: Enable ufw
  ufw:
    state: enabled

- name: Install fail2ban
  apt:
    name: fail2ban
    state: present
  when: ansible_os_family == "Debian"

- name: Install fail2ban
  yum:
    name: fail2ban
    state: present
  when: ansible_os_family == "RedHat"

- name: Configure SSH jail
  lineinfile:
    path: /etc/fail2ban/jail.conf
    regexp: "^[# ]*ssh"
    line: "[ssh]
    port = ssh
    filter = ssh
    logpath = /var/log/auth.log
    maxretry = 3
    bantime = 600"
    state: present
  when: ansible_os_family == "Debian"

- name: Configure SSH jail
  lineinfile:
    path: /etc/fail2ban/jail.d/sshd.conf
    regexp: "^# "
    line: "port = ssh
           filter = sshd
           logpath = /var/log/secure
           maxretry = 3
           bantime = 600"
    state: present
  when: ansible_os_family == "RedHat"

- name: Restart fail2ban service
  systemd:
    name: fail2ban
    state: restarted
