---
- name: Download AlbyHub
  command: "curl -s -L -o {{ albyhub_dl_dir }}/{{ albyhub_pkg }} {{ albyhub_url }}"
  args:
    creates: "{{ albyhub_dl_dir }}/server-linux-x86_64.tar.bz2"

- name: Extract AlbyHub
  unarchive:
    src: "{{ albyhub_dl_dir }}/server-linux-x86_64.tar.bz2"
    dest: "{{ albyhub_dl_dir }}"
    remote_src: yes
    mode: '0755'

- name: Move AlbyHub binary
  copy:
    src: "{{ albyhub_dl_dir }}/bin/albyhub"
    dest: "/usr/local/bin/albyhub"
    remote_src: yes
    mode: '0755'

- name: Move LDK library
  copy:
    src: "{{ albyhub_dl_dir }}/lib/libldk_node.so"
    dest: "/usr/local/lib/libldk_node.so"
    remote_src: yes
    mode: '0644'

- name: create systemd unit file
  template:
    src: albyhub.service.j2
    dest: /etc/systemd/system/albyhub.service
    mode: '0644'
  notify: 
    - reload systemd
    - start albyhub
    # - cleanup albyhub
