---
- name: create albyhub directories
  file:
    path: "{{ item }}"
    state: directory
    owner: bitcoin
    group: bitcoin
  with_items:
    - /opt/albyhub

- name: install bzip2
  become: true
  ansible.builtin.apt:
    name: bzip2
- name: install unzip
  become: true
  ansible.builtin.apt:
    name: unzip

# - include_tasks: "{{ playbook_dir }}/tasks/wait_tor.yml"
- include_tasks: install_albyhub.yml
