
# fixme sudo -u debian-tor tor
# - name: create torrc.fulcrum.conf
#   template:
#     src: torrc.fulcrum.conf.j2
#     dest: /etc/torrc.d/torrc.fulcrum.conf
#     owner: debian-tor
#     group: debian-tor
#     mode: '0644'
#   tags:
#     - tor

- name: Add HiddenServiceDir and HiddenServicePort torrc
  blockinfile:
    path: /etc/tor/torrc
    insertafter: EOF
    state: present
    marker: "# {mark} ANSIBLE MANAGED BLOCK - fulcrum"
    create: yes
    backup: yes
    append_newline: true
    block: |
      HiddenServiceDir /var/lib/tor/fulcrum/
      HiddenServicePort 50002 127.0.0.1:50002

- name: restart tor
  systemd:
    name: tor
    state: restarted

- name: wait for tor hidden service hostname file to be created in /var/lib/tor/fulcrum
  ansible.builtin.wait_for:
    path: /var/lib/tor/fulcrum/hostname
    state: present
    timeout: 300
  register: tor_hostname_wait_result
  tags:
    - fulcrum

- name: handle errors
  ansible.builtin.fail:
    msg: "Tor hidden service hostname file was not created within the specified time"
  when: tor_hostname_wait_result is failed
  tags:
    - fulcrum

- name: Get Tor hostname
  command: cat /var/lib/tor/fulcrum/hostname
  register: tor_hostname
  tags:
    - fulcrum

- debug:
    var: tor_hostname.stdout
  tags:
    - fulcrum

- name: create fulctrum directories
  file:
    path: "{{ item }}"
    state: directory
    owner: bitcoin
    group: bitcoin
  with_items:
    - /opt/fulcrum
    - /opt/fulcrum/.cache
    - /opt/fulcrum/data
    - /tmp/fulcrum
  tags:
    - fulcrum

- name: create fulcrum.conf
  template:
    src: fulcrum.conf.j2
    dest: /opt/fulcrum/data/fulcrum.conf
    owner: bitcoin
    group: bitcoin
    mode: '0644'
  tags:
    - fulcrum

- include_tasks: "{{ playbook_dir }}/tasks/wait_tor.yml"

- name: Check if {{ fulcrum_version }} installed
  stat:
    path: "{{ fulcrum_version_id }}"
  register: fulcrum_version_stat

- name: install fulcrum-{{ fulcrum_version }}
  when: fulcrum_version_stat.stat.exists == false
  block:
    - name: download fulcrum via tor
      command: torsocks curl -s -L -o /tmp/fulcrum/Fulcrum-{{ fulcrum_version }}-x86_64-linux.tar.gz https://github.com/cculianu/Fulcrum/releases/download/v{{ fulcrum_version }}/Fulcrum-{{ fulcrum_version }}-x86_64-linux.tar.gz
      args:
        creates: /tmp/fulcrum/Fulcrum-{{ fulcrum_version }}-x86_64-linux.tar.gz

    - name: download fulcrum checksums via tor
      command: torsocks curl -s -L -o /tmp/fulcrum/Fulcrum-{{ fulcrum_version }}-shasums.txt https://github.com/cculianu/Fulcrum/releases/download/v{{ fulcrum_version }}/Fulcrum-{{ fulcrum_version }}-shasums.txt
      args:
        creates: /tmp/fulcrum/Fulcrum-{{ fulcrum_version }}-shasums.txt

    - name: download fulcrum signature
      command: torsocks curl -s -L -o /tmp/fulcrum/Fulcrum-{{ fulcrum_version }}-shasums.txt.asc https://github.com/cculianu/Fulcrum/releases/download/v{{ fulcrum_version }}/Fulcrum-{{ fulcrum_version }}-shasums.txt.asc
      args:
        creates: /tmp/fulcrum/Fulcrum-{{ fulcrum_version }}-shasums.txt.asc

    - name: verify sha256sum
      command: sha256sum --check --ignore-missing /tmp/fulcrum/Fulcrum-{{ fulcrum_version }}-shasums.txt
      args:
        chdir: /tmp/fulcrum
      register: package_checksum

    - name: assert sha256sum contains "OK"
      assert:
        that: package_checksum.stdout.find('OK') != -1
        msg: "Package checksum verification failed. Please verify the package checksum manually."
 
    - name: download fulcrum pgp key
      get_url:
        url: https://fulcrumserver.org/calinkey.txt
        dest: /tmp/fulcrum/calinkey.txt

    - name: gpg import fulcrum pgp key
      command: gpg --import /tmp/fulcrum/calinkey.txt

    - name: check fulcrum signature
      command: gpg --verify /tmp/fulcrum/Fulcrum-{{ fulcrum_version }}-shasums.txt.asc
      args:
        chdir: /tmp/fulcrum

    - name: Generate self-signed RSA key if not exists
      become: yes
      command: openssl genrsa -out /opt/fulcrum/fulcrum.key 2048
      args:
        creates: /opt/fulcrum/fulcrum.key

    - name: Set ownership and permissions for fulcrum.key
      become: yes
      ansible.builtin.file:
        path: /opt/fulcrum/fulcrum.key
        owner: bitcoin
        group: bitcoin
        mode: '0600'

    - name: create openssl self-signed cert conf
      template:
        src: self-signed-cert.conf.j2
        dest: /opt/fulcrum/localhost.conf
        owner: bitcoin
        group: bitcoin
        mode: '0644'

    - name: Generate self-signed RSA key if not exists
      become: yes
      command: openssl req -new -x509 -sha256 -key /opt/fulcrum/fulcrum.key -out /opt/fulcrum/fulcrum.cert -days 3650 -config /opt/fulcrum/localhost.conf
      args:
        creates: /opt/fulcrum/fulcrum.cert

    - name: Set ownership and permissions for fulcrum.cert
      become: yes
      ansible.builtin.file:
        path: /opt/fulcrum/fulcrum.cert
        owner: bitcoin
        group: bitcoin
        mode: '0600'

    - name: extract fulcrum
      unarchive:
        src: /tmp/fulcrum/Fulcrum-{{ fulcrum_version }}-x86_64-linux.tar.gz
        dest: /opt/fulcrum
        owner: bitcoin
        group: bitcoin
        remote_src: true
      # notify: 
      #   - cleanup fulcrum files

- name: create systemd unit file
  template:
    src: fulcrum.service.j2
    dest: /etc/systemd/system/fulcrum.service
    mode: '0644'
  notify: 
    - reload systemd
    - restart fulcrum
