services:
  uptime-kuma:
    # https://hub.docker.com/r/louislam/uptime-kuma/tags
    image: louislam/uptime-kuma:1-alpine
    # user: "${UID:-1002}:${GID:-988}"
    volumes:
      - ${BASE_DIR:-.}/uptime-kuma/data:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped
