---
global:
  scrape_interval: 30s
  scrape_timeout: 10s

#rule_files:
#  - alert.yml

scrape_configs:
  - job_name: otel-collector
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'otel-collector:8889'

