# Running `docker-compose up` will create/use the "trilium-data" directory in the user home
# Run `TRILIUM_DATA_DIR=/path/of/your/choice docker-compose up` to set a different directory
services:
  trilium:
    image: zadam/trilium
    restart: always
    # user: "${UID}:${GID}"
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
      - USER_UID=${UID}
      - USER_GID=${GID}
    ports:
      - "8180:8080"
    volumes:
      - ${BASE_DIR:-.}/trilium-data:/home/node/trilium-data
