set dotenv-load

deploy_host := "$HOST-docker"

deploy:
  @docker context create {{deploy_host}} --docker "host=ssh://{{deploy_host}}" || true
  @docker context use {{deploy_host}}
  docker compose up -d --force-recreate
  docker compose ps
