---
version: '3'
volumes:
  music-vol:
    driver_opts:
      type: "nfs"
      o: "addr=${NAS_DOMAIN},nolock,soft,rw"
      device: ":/volume1/shared/30_Media/34_Audio/Music/"
  roon-server-data-vol:
    name: roon-server-data
  roon-server-cache-vol:
    driver_opts:
      type: "nfs"
      o: "addr=${NAS_DOMAIN},nolock,soft,rw"
      device: ":/volume1/shared/30_Media/34_Audio/roon/RoonOnNAS/"
services:
  roon:
    container_name: roon-server
    image: elgeeko/roon-server:latest  # src: https://github.com/elgeeko1/roon-server-docker
    restart: unless-stopped
    network_mode: host
    privileged: true
    user: roon
    volumes:
      - /volume1/shared/30_Media/34_Audio/Music/:/music:ro 
      - /volume1/Docker/Roon/RoonServer:/opt/RoonServer
      - /volume1/shared/30_Media/34_Audio/roon/RoonOnNAS/:/var/roon
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    labels:
      - com.centurylinklabs.watchtower.enable=true"
