set dotenv-load

deploy_host := "$HOST-docker"

deploy:
  @docker context create monitoring --docker "host=ssh://{{deploy_host}}" || true
  @docker context use monitoring
  scp -r ./otelcol {{deploy_host}}:$BASE_DIR/
  BASE_DIR=$BASE_DIR docker compose up -d --force-recreate
  docker compose ps
