set dotenv-load

deploy_host := "$HOST-docker"

set-context:
  @docker context create monitoring --docker "host=ssh://{{deploy_host}}" || true
  @docker context use monitoring

push-files:
  @scp -r ./otelcol {{deploy_host}}:$BASE_DIR/
  @scp -r ./prometheus {{deploy_host}}:$BASE_DIR/
  @scp -r ./grafana {{deploy_host}}:$BASE_DIR/
  @scp -r ./alertmanager/ {{deploy_host}}:$BASE_DIR/

save-secrets:
  sops -e .env > .env.enc

deploy: set-context push-files
  docker compose pull
  BASE_DIR=$BASE_DIR docker compose up -d --force-recreate
  docker compose ps
